services:
  mysql:
    image: mysql:latest
    container_name: mysql-instance
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/todo.sql:/docker-entrypoint-initdb.d/todo.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  todoserver:
    build: .
    container_name: todo-server
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_NAME: testdb
      DB_USER: user
      DB_PASS: pass
      DB_HOST: mysql
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
